/**
 * Telnyx webhook signature verification — Ed25519.
 *
 * WHY THIS EXISTS (and why it is not optional on a mutating webhook):
 *
 * A Telnyx webhook is a PUBLIC HTTPS endpoint — Telnyx isn't logged in, so it
 * can't present a JWT, which is why these routes sit in PUBLIC_ROUTES. That
 * means anyone on the internet can POST JSON to them. The `from` phone number in
 * an inbound-SMS payload is therefore just *a string in the request body*: in a
 * forged request no handset, SIM, or carrier was ever involved, so nothing
 * vouches for it.
 *
 * Without verification, an inbound-SMS route is not "an SMS handler" — it is an
 * unauthenticated public API whose contract is "mutate state on behalf of any
 * phone number you name". Both inputs are guessable (the `to` number is the
 * business's public phone number; `from` numbers are just customer numbers), so
 * a forged POST costs nothing and sends no text.
 *
 * The signature is what turns "the from-number is attacker-supplied" into "the
 * from-number came from Telnyx, who got it from the carrier".
 *
 * ── HISTORY: this was implemented against the WRONG ALGORITHM ──────────────
 *
 * The original version (and the pre-existing /telnyx/status webhook it was
 * copied from) verified an HMAC-SHA256 over `timestamp|rawBody` against a shared
 * secret, read from a `telnyx-signature: t=…,v1=…` header. That is STRIPE's
 * scheme, not Telnyx's. Telnyx does not offer HMAC at all.
 *
 * It was never caught because TELNYX_WEBHOOK_SECRET was never set in any
 * environment, so the code always took its "secret unset → skip verification"
 * branch and the HMAC path never executed against a real Telnyx request. The
 * unit tests passed only because they SIGNED with the same wrong algorithm they
 * VERIFIED with — self-consistent, and wrong.
 *
 * Had the secret simply been set, the fail-closed inbound route would have 403'd
 * every genuine Telnyx webhook (the `telnyx-signature` header it looked for does
 * not exist), silently killing STOP handling.
 *
 * ── WHAT TELNYX ACTUALLY DOES ─────────────────────────────────────────────
 *
 *   headers:  telnyx-signature-ed25519  (base64 Ed25519 signature)
 *             telnyx-timestamp          (unix seconds)
 *   signed:   `${timestamp}|${rawBody}`
 *   key:      Telnyx's account-wide Ed25519 PUBLIC key.   (TELNYX_PUBLIC_KEY)
 *
 * It is a PUBLIC key, not a shared secret: Telnyx generated the keypair, holds the
 * private half, and signs with it. We only ever VERIFY. Nothing is generated by us,
 * nothing is uploaded to them, and the value is not sensitive.
 *
 * GETTING IT: the docs say Mission Control → Keys & Credentials → Public Key, but the
 * redesigned portal (2026-07-12) has no such page. Fetch it from the API instead:
 *
 *   curl -H "Authorization: Bearer $TELNYX_API_KEY" https://api.telnyx.com/v2/public_key
 *   → { "data": { "public": "<base64>", "record_type": "public_key", ... } }
 *
 * https://developers.telnyx.com/docs/messaging/messages/receiving-webhooks
 *
 * Two rules the callers must honor:
 *   1. Verify BEFORE parsing/acting on the payload — an unsigned caller must
 *      never reach the DB path.
 *   2. Verify against the EXACT bytes received (`req.rawBody`), never a
 *      re-stringified `req.body` — key order and whitespace need not survive a
 *      parse/serialize round-trip, and Telnyx signed the original bytes.
 */
import { createPublicKey, verify as cryptoVerify, type KeyObject } from 'crypto';

export type TelnyxSignatureResult =
  | { valid: true }
  | {
      valid: false;
      reason:
        | 'missing_raw_body'
        | 'missing_signature'
        | 'missing_timestamp'
        | 'stale_timestamp'
        | 'bad_public_key'
        | 'signature_mismatch';
    };

/**
 * Telnyx's portal hands you the public key as bare base64 — the raw 32 bytes of
 * an Ed25519 key, with no PEM armor and no DER structure. Node's
 * createPublicKey() needs a structured key, so wrap the raw bytes in the fixed
 * SPKI DER prefix that identifies them as Ed25519.
 *
 * A PEM-armored key is also accepted, since some Telnyx surfaces/docs show one
 * and an operator pasting either form should just work.
 */
const ED25519_SPKI_DER_PREFIX = Buffer.from('302a300506032b6570032100', 'hex');

const keyCache = new Map<string, KeyObject | null>();

export function loadTelnyxPublicKey(raw: string): KeyObject | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;

  const cached = keyCache.get(trimmed);
  if (cached !== undefined) return cached;

  let key: KeyObject | null = null;
  try {
    if (trimmed.includes('BEGIN PUBLIC KEY')) {
      key = createPublicKey(trimmed);
    } else {
      const bytes = Buffer.from(trimmed, 'base64');
      // A raw Ed25519 public key is exactly 32 bytes. Anything else means the
      // operator pasted the wrong value (an API key, a private key, a truncated
      // paste) — fail rather than construct a key that can never verify.
      if (bytes.length !== 32) {
        keyCache.set(trimmed, null);
        return null;
      }
      key = createPublicKey({
        key: Buffer.concat([ED25519_SPKI_DER_PREFIX, bytes]),
        format: 'der',
        type: 'spki',
      });
    }
  } catch {
    key = null;
  }

  keyCache.set(trimmed, key);
  return key;
}

/** How far out of date a signed timestamp may be. Bounds replay of a captured
 *  webhook. Telnyx retries for a while, so this can't be too tight; 5 minutes
 *  matches the common provider convention. */
export const TELNYX_TIMESTAMP_TOLERANCE_SECONDS = 300;

/**
 * Verify a Telnyx Ed25519 webhook signature against the raw request bytes.
 *
 * `nowSeconds` is injectable so the staleness check is testable without faking
 * the clock globally.
 */
export function verifyTelnyxSignature(params: {
  rawBody: Buffer | string | undefined;
  signatureHeader: string | undefined; // telnyx-signature-ed25519
  timestampHeader: string | undefined; // telnyx-timestamp
  publicKey: string;
  nowSeconds?: number;
  toleranceSeconds?: number;
}): TelnyxSignatureResult {
  const {
    rawBody,
    signatureHeader,
    timestampHeader,
    publicKey,
    nowSeconds = Math.floor(Date.now() / 1000),
    toleranceSeconds = TELNYX_TIMESTAMP_TOLERANCE_SECONDS,
  } = params;

  const raw =
    typeof rawBody === 'string'
      ? rawBody
      : rawBody instanceof Buffer
        ? rawBody.toString('utf8')
        : null;
  if (raw === null) return { valid: false, reason: 'missing_raw_body' };

  if (!signatureHeader) return { valid: false, reason: 'missing_signature' };
  if (!timestampHeader) return { valid: false, reason: 'missing_timestamp' };

  const ts = Number(timestampHeader);
  if (!Number.isFinite(ts)) return { valid: false, reason: 'missing_timestamp' };
  // Reject a signature that is too old (replay of a captured webhook) or too far
  // in the future (a skewed/forged timestamp). The signature covers the
  // timestamp, so an attacker can't simply rewrite it to something current.
  if (Math.abs(nowSeconds - ts) > toleranceSeconds) {
    return { valid: false, reason: 'stale_timestamp' };
  }

  const key = loadTelnyxPublicKey(publicKey);
  if (!key) return { valid: false, reason: 'bad_public_key' };

  let signature: Buffer;
  try {
    signature = Buffer.from(signatureHeader, 'base64');
  } catch {
    return { valid: false, reason: 'signature_mismatch' };
  }
  // An Ed25519 signature is exactly 64 bytes. cryptoVerify tolerates the wrong
  // length by returning false, but checking makes the failure reason honest.
  if (signature.length !== 64) return { valid: false, reason: 'signature_mismatch' };

  // Ed25519 verification is constant-time inside libsodium/OpenSSL, and the key
  // is PUBLIC anyway — there is no secret here for a timing oracle to leak, so
  // no timingSafeEqual dance is needed (unlike the HMAC scheme this replaced).
  const message = Buffer.from(`${timestampHeader}|${raw}`, 'utf8');
  let ok: boolean;
  try {
    ok = cryptoVerify(null, message, key, signature);
  } catch {
    return { valid: false, reason: 'signature_mismatch' };
  }

  return ok ? { valid: true } : { valid: false, reason: 'signature_mismatch' };
}

// Keyword classification lives in ./smsKeywords — the ONE source of truth shared
// with ConsentService. Re-exported here so existing importers of this module keep
// working. Duplicating the word lists is exactly how the webhook and the consent
// service came to disagree about what START means (see PR #238).
export {
  classifySmsKeyword,
  OPT_OUT_WORDS,
  OPT_IN_WORDS,
  isOptOutKeyword,
  type SmsKeyword,
} from './smsKeywords';
