import { withSentryConfig } from '@sentry/nextjs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** @type {import('next').NextConfig} */
const nextConfig = {
  // output: 'standalone' + outputFileTracingRoot solves the Railway deployment
  // issue where dynamic (lazy-loaded) chunks were generated by the build but not
  // preserved in the deployed container — all 14 async chunks 404'd, breaking
  // every feature tab. Standalone mode bundles all files the server needs into
  // .next/standalone/, guaranteeing chunk files survive the deploy.
  //
  // outputFileTracingRoot = repo root so ../shared/* imports are traced and
  // included. With this set, server.js lands at
  //   .next/standalone/dashboard/server.js   (mirrors repo-root relative path)
  // and the Railway start command runs:
  //   HOSTNAME=0.0.0.0 node dashboard/.next/standalone/dashboard/server.js
  // See dashboard/railway.json for the full build + copy + start commands.
  output: 'standalone',
  outputFileTracingRoot: path.join(__dirname, '../'),
  eslint: {
    // Test files have cosmetic `any` warnings — don't block production builds
    ignoreDuringBuilds: true,
  },
};

// withSentryConfig is a no-op at runtime when SENTRY_DSN is unset; the
// source-map upload + tunnel route are skipped without an auth token.
// Keep the wrap unconditional so prod-style builds don't behave
// differently from local builds at the file layer.
export default withSentryConfig(nextConfig, {
  silent: !process.env.SENTRY_AUTH_TOKEN,
  // Source maps are only uploaded when SENTRY_AUTH_TOKEN is set (CI/CD).
  // The wizard's default config tries to upload on every build, which
  // makes local builds noisy and CI builds slow when the token is
  // missing — gate it explicitly.
  widenClientFileUpload: false,
  tunnelRoute: '/monitoring',
  disableLogger: true,
  automaticVercelMonitors: false,
});
