/**
 * E2E coverage for the super-admin tenant-delete cascade. Pins that
 * `DELETE /tenants/:id` removes the tenant row AND every dependent row
 * across the schema's 20+ tenant-scoped tables via FK CASCADE — not just
 * the tenant record itself.
 *
 * Why this exists: `docs/TODO.md` P2 "Tenant delete cascade" — backend
 * unit tests verify the DELETE route returns success, and the
 * `cleanTenantData` fixture relies on cascade for test teardown, but
 * nothing pins the end-to-end contract that a real super-admin delete
 * action removes all customer/employee/appointment data. If a future
 * migration adds a tenant-scoped table without `ON DELETE CASCADE`, the
 * delete would succeed but leave orphan rows pointing at a dead tenant
 * — a data-integrity bug masquerading as "GDPR-clean".
 *
 * Design notes:
 *   - Seeds a fresh tenant via /register, then seeds every category of
 *     dependent we ship in production: users, services/resources/
 *     employees/customers (entities), employee_schedule (shifts),
 *     appointments (central data), service_employee + service_resource
 *     (mappings), audit_logs + record_versions (auto-generated by
 *     triggers on the data inserts above).
 *   - Calls DELETE /tenants/:id as super-admin (the only role allowed
 *     past `requireSuperAdmin`). Super-admin token comes from /login
 *     against the seed admin user — that role's authority is the
 *     contract this test exercises.
 *   - Counts each table both pre- and post-delete. Pre>0 proves the
 *     seed actually inserted rows, so post==0 means "cascade worked"
 *     rather than "table was empty all along".
 *   - The test owns its data lifecycle: pre-existing rows in any of
 *     these tables (for OTHER tenants) must be untouched after delete.
 *     A second tenant is seeded as a "bystander" sanity check —
 *     verifies the cascade is scoped to the deleted tenant_id, not a
 *     schema-wide DELETE.
 */
import { test, expect, type APIRequestContext } from '@playwright/test';
import { Pool } from 'pg';
import {
  BACKEND_URL,
  PG_URL,
  registerFreshTenant,
  seedBookingScenario,
  seedAppointment,
  cleanTenantData,
  isoDateDaysFromNow,
  type RegisteredTenant,
} from './helpers/fixtures';

const ADMIN_EMAIL = 'admin@secretaryhq.com';
const ADMIN_PASSWORD = 'password';

let pool: Pool;
let superAdminToken: string;

test.beforeAll(async ({ request }) => {
  pool = new Pool({ connectionString: PG_URL });
  // Acquire super-admin JWT directly via /login — the DELETE route
  // requires super-admin, and the registered-fresh-tenant owner can't
  // delete its own tenant (the owner role passes requireAuth but not
  // requireSuperAdmin, by design).
  const res = await request.post(`${BACKEND_URL}/login`, {
    headers: { 'Content-Type': 'application/json' },
    data: { email: ADMIN_EMAIL, password: ADMIN_PASSWORD },
  });
  expect(res.status(), 'super-admin login must succeed for the cascade test to run').toBe(200);
  const body = await res.json();
  expect(body.token, 'login response must include a JWT').toBeTruthy();
  superAdminToken = body.token as string;
});
test.afterAll(async () => {
  await pool.end();
});

/**
 * Snapshot row counts for every tenant-scoped table the test cares
 * about. Returns an object keyed by table name so the test can compare
 * pre/post diffs and the error message names the offending table.
 */
async function countTenantRows(tenantId: string): Promise<Record<string, number>> {
  const tables = [
    'users',
    'services',
    'resources',
    'employees',
    'customers',
    'employee_schedule',
    'appointments',
    'service_employee',
    'service_resource',
    'audit_log',
    'record_versions',
  ];
  const counts: Record<string, number> = {};
  for (const t of tables) {
    const r = await pool.query(`SELECT count(*)::int AS n FROM ${t} WHERE tenant_id = $1`, [tenantId]);
    counts[t] = r.rows[0].n;
  }
  return counts;
}

async function tenantExists(tenantId: string): Promise<boolean> {
  const r = await pool.query('SELECT 1 FROM tenants WHERE id = $1', [tenantId]);
  return r.rowCount === 1;
}

async function deleteTenantAsSuperAdmin(
  req: APIRequestContext,
  tenantId: string
): Promise<{ status: number; body: Record<string, unknown> }> {
  const res = await req.delete(`${BACKEND_URL}/tenants/${tenantId}`, {
    headers: { Authorization: `Bearer ${superAdminToken}` },
  });
  return { status: res.status(), body: await res.json() };
}

// ────────────────────────────────────────────────────────────────────────────
// 1. HAPPY: full cascade across every tenant-scoped table
// ────────────────────────────────────────────────────────────────────────────
test('cascade: super-admin delete drops the tenant AND all dependent rows across 11 tables', async ({ request }) => {
  // WHO: super-admin retiring a customer tenant (offboarding / GDPR
  //       deletion request / failed-trial cleanup).
  // WHAT: seed a tenant with realistic dependents — services, resources,
  //       employees, customers, shifts, appointments, mapping rows,
  //       audit/version-history (auto-generated by INSERT triggers) —
  //       then DELETE /tenants/:id as super-admin. Verify the tenant
  //       row is gone AND every count in countTenantRows() returns 0.
  // WHEN: any tenant deletion through the admin surface.
  // WHERE: src/routes/tenants.ts `DELETE /tenants/:id` →
  //       `DELETE FROM tenants WHERE id = $1` → FK CASCADE.
  // WHY: the route does nothing but DELETE the parent row. If a future
  //       migration adds a tenant-scoped table without `ON DELETE
  //       CASCADE`, the delete would succeed at the API layer but leave
  //       orphan rows in that table — bad for GDPR ("we deleted the
  //       customer's data" is now a lie), bad for schema integrity
  //       (rows reference a tenant_id that's been reused for someone
  //       else), and especially bad if RLS isolation depends on the
  //       tenant existing. Pinning row counts == 0 across every
  //       tenant-scoped table is the only way to catch that.
  let tenant: RegisteredTenant | null = null;
  try {
    tenant = await registerFreshTenant(request);
    const date = isoDateDaysFromNow(7);
    const seed = await seedBookingScenario(request, pool, tenant.token, tenant.tenantId, {
      employees: ['Cascade Tech 1', 'Cascade Tech 2'],
      resources: ['Cascade Bay'],
      shiftDates: [date],
    });

    // One appointment so audit_logs + record_versions trigger rows
    // land in the count. Without an INSERT into appointments, both
    // audit tables stay empty and we can't tell whether they
    // cascaded or just had nothing to begin with.
    await seedAppointment(pool, tenant.tenantId, {
      resourceId: seed.resourceIds[0],
      customerId: seed.customerId,
      employeeId: seed.employeeIds[0],
      startTime: `${date}T14:00:00.000Z`,
      endTime: `${date}T14:30:00.000Z`,
      description: 'cascade-test appointment',
    });

    // Pre-condition: every relevant table has > 0 rows for this tenant.
    // The /register flow alone seeds users (the owner) + services
    // (from the auto-seed template); seedBookingScenario adds the rest.
    // If a category somehow stays at 0, the post-delete assertion
    // would pass for the wrong reason ("table was empty"); guard
    // against that here.
    const pre = await countTenantRows(tenant.tenantId);
    expect(pre.users, 'register must seed the owner user').toBeGreaterThan(0);
    expect(pre.employees, 'seed must insert employees').toBeGreaterThan(0);
    expect(pre.resources, 'seed must insert resources').toBeGreaterThan(0);
    expect(pre.customers, 'seed must insert a customer').toBeGreaterThan(0);
    expect(pre.employee_schedule, 'seed must insert shifts').toBeGreaterThan(0);
    expect(pre.appointments, 'seed must insert an appointment').toBeGreaterThan(0);
    expect(pre.audit_log, 'INSERT triggers must record audit rows').toBeGreaterThan(0);
    expect(pre.record_versions, 'INSERT triggers must record version rows').toBeGreaterThan(0);
    // service_employee/service_resource/services are not always pre-
    // populated for a default-template registration (auto-seed varies
    // by template); don't require >0 there, but they must drop to 0
    // post-delete if any rows existed.

    expect(await tenantExists(tenant.tenantId), 'tenant must exist before DELETE').toBe(true);

    const del = await deleteTenantAsSuperAdmin(request, tenant.tenantId);
    expect(del.status, `DELETE must succeed; body=${JSON.stringify(del.body)}`).toBe(200);
    expect(del.body.success).toBe(true);

    // Tenant row itself is gone
    expect(await tenantExists(tenant.tenantId), 'tenant must be gone after DELETE').toBe(false);

    // FK CASCADE wiped every dependent row. Iterate so any non-zero
    // count names the offending table in the assertion message —
    // saves the next debugger ten minutes of guessing.
    const post = await countTenantRows(tenant.tenantId);
    for (const [table, count] of Object.entries(post)) {
      expect(count, `cascade left ${count} orphan row(s) in '${table}' (pre=${pre[table]})`).toBe(0);
    }

    tenant = null; // tenant is gone; skip the finally cleanup
  } finally {
    // Belt-and-suspenders: if anything before the DELETE failed, the
    // tenant still exists and we'd leak its seed rows. cleanTenantData
    // is the same single-statement cascade DELETE.
    if (tenant) await cleanTenantData(pool, tenant.tenantId);
  }
});

// ────────────────────────────────────────────────────────────────────────────
// 2. ISOLATION: bystander tenant survives the cascade unchanged
// ────────────────────────────────────────────────────────────────────────────
test('isolation: deleting one tenant does not touch any other tenant\'s rows', async ({ request }) => {
  // WHO: super-admin retiring tenant A while tenant B is operating
  //       normally (the typical multi-tenant production case).
  // WHAT: seed two independent fresh tenants A + B with the same
  //       category of dependents. DELETE tenant A. Verify B's row
  //       counts are exactly the same after the delete as before.
  // WHEN: any tenant deletion in a multi-tenant database.
  // WHERE: FK CASCADE scoping — the DELETE FROM tenants WHERE id =
  //       $1 must affect only that tenant's row, not the whole table.
  // WHY: a regression where the cascade somehow scoped wider (a
  //       trigger fires DELETE FROM appointments without a WHERE
  //       tenant_id = OLD.id, or an RLS-bypass policy is mis-written)
  //       would wipe data for every customer the moment any tenant
  //       got deleted. The simple cascade SQL today is safe by
  //       construction, but the test pins the contract so a future
  //       trigger-based replacement can't quietly broaden it.
  let tenantA: RegisteredTenant | null = null;
  let tenantB: RegisteredTenant | null = null;
  try {
    tenantA = await registerFreshTenant(request);
    tenantB = await registerFreshTenant(request);
    const date = isoDateDaysFromNow(7);

    // Seed both tenants identically so the comparison is apples-to-apples.
    const seedA = await seedBookingScenario(request, pool, tenantA.token, tenantA.tenantId, {
      employees: ['A Tech'], resources: ['A Bay'], shiftDates: [date],
    });
    const seedB = await seedBookingScenario(request, pool, tenantB.token, tenantB.tenantId, {
      employees: ['B Tech'], resources: ['B Bay'], shiftDates: [date],
    });
    await seedAppointment(pool, tenantA.tenantId, {
      resourceId: seedA.resourceIds[0],
      customerId: seedA.customerId,
      employeeId: seedA.employeeIds[0],
      startTime: `${date}T10:00:00.000Z`,
      endTime: `${date}T10:30:00.000Z`,
      description: 'A: cascade test',
    });
    await seedAppointment(pool, tenantB.tenantId, {
      resourceId: seedB.resourceIds[0],
      customerId: seedB.customerId,
      employeeId: seedB.employeeIds[0],
      startTime: `${date}T11:00:00.000Z`,
      endTime: `${date}T11:30:00.000Z`,
      description: 'B: should survive A delete',
    });

    const preB = await countTenantRows(tenantB.tenantId);
    // Sanity: B has the expected rows pre-delete
    expect(preB.employees, 'B should have its seeded employee').toBeGreaterThan(0);
    expect(preB.appointments, 'B should have its seeded appointment').toBeGreaterThan(0);

    // Delete A. B must be untouched.
    const del = await deleteTenantAsSuperAdmin(request, tenantA.tenantId);
    expect(del.status).toBe(200);
    expect(await tenantExists(tenantA.tenantId), 'A must be gone').toBe(false);
    expect(await tenantExists(tenantB.tenantId), 'B must still exist').toBe(true);

    const postB = await countTenantRows(tenantB.tenantId);
    for (const [table, count] of Object.entries(postB)) {
      expect(
        count,
        `bystander tenant B's '${table}' count changed from ${preB[table]} to ${count} after deleting A — cascade scoped wider than tenant A's id`
      ).toBe(preB[table]);
    }

    tenantA = null;
  } finally {
    if (tenantA) await cleanTenantData(pool, tenantA.tenantId);
    if (tenantB) await cleanTenantData(pool, tenantB.tenantId);
  }
});

// ────────────────────────────────────────────────────────────────────────────
// 3. AUTHZ: non-super-admin DELETE returns 403, tenant + data untouched
// ────────────────────────────────────────────────────────────────────────────
test('authz: a tenant owner cannot delete their own tenant — returns 403, tenant survives', async ({ request }) => {
  // WHO: a tenant owner (not super-admin) who tries to call DELETE
  //       /tenants/:id with their own token.
  // WHAT: the requireSuperAdmin gate must reject with 403 BEFORE the
  //       DELETE SQL runs. The tenant and all its rows must still be
  //       intact.
  // WHEN: any non-super-admin authenticated request to the route.
  // WHERE: src/routes/tenants.ts:64 `if (!requireSuperAdmin(req, reply)) return;`
  // WHY: pre-2026-05-06, `/tenants/*` admin routes only checked
  //       `requireAuth` not `requireSuperAdmin` — any authenticated
  //       user could DELETE any tenant. That hole was closed in the
  //       multi-tenant isolation pass and unit-tested in
  //       `multi-tenant-isolation.test.ts`. This E2E pins the same
  //       contract at the full request-response level: not just
  //       "returns 403" but "tenant still exists + data still
  //       there" — defense-in-depth that the 403 fires before any
  //       DB mutation.
  let tenant: RegisteredTenant | null = null;
  try {
    tenant = await registerFreshTenant(request);
    const date = isoDateDaysFromNow(7);
    const seed = await seedBookingScenario(request, pool, tenant.token, tenant.tenantId, {
      employees: ['Owner Test'], resources: ['Owner Bay'], shiftDates: [date],
    });
    await seedAppointment(pool, tenant.tenantId, {
      resourceId: seed.resourceIds[0],
      customerId: seed.customerId,
      employeeId: seed.employeeIds[0],
      startTime: `${date}T13:00:00.000Z`,
      endTime: `${date}T13:30:00.000Z`,
      description: 'owner-only test',
    });

    const pre = await countTenantRows(tenant.tenantId);

    // Owner token — NOT super-admin.
    const res = await request.delete(`${BACKEND_URL}/tenants/${tenant.tenantId}`, {
      headers: { Authorization: `Bearer ${tenant.token}` },
    });
    expect(res.status(), 'owner DELETE must be rejected at the authz gate').toBe(403);

    // The 403 must fire BEFORE any DELETE SQL runs. If the gate is
    // somehow only at the response layer (e.g. it sends 403 but lets
    // the handler continue), this would catch it.
    expect(await tenantExists(tenant.tenantId), 'tenant must still exist after a rejected delete').toBe(true);
    const post = await countTenantRows(tenant.tenantId);
    for (const [table, count] of Object.entries(post)) {
      expect(
        count,
        `'${table}' count changed from ${pre[table]} to ${count} after a rejected delete — gate is not blocking the SQL`
      ).toBe(pre[table]);
    }
  } finally {
    if (tenant) await cleanTenantData(pool, tenant.tenantId);
  }
});
