name: Check Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm & dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm -w install --frozen-lockfile
      - name: Check docs location
        run: pnpm -s check-docs
